### PR TITLE
Feature/wookie

### LINKED ISSUE #27: ?format=wookiee does not work
Hi @astagi, the url formatting does not properly work.

I tried it out and I get 404 errors. Can you please write a test that mimics the tests we have for urls, but with your rendering? That should help you understand what the bug is, and then fix it.

I've rolled back to a previous version for now.

### PR DESCRIPTION
**Pull request by astagi**
Closes #27

### CODE REVIEW

**Comment by phalt** [comment]
:tada: Woo! I'll check this out some time this week

**Comment by astagi** [comment]
:+1:

**Comment by phalt** [comment]
Let's try this out this time :)

**Comment by phalt** [comment]
@astagi deployed!

**Comment by astagi** [comment]
Thanks @phalt ! :) just a question: why did you push a "fix broken encoding"? I just let the same JSONRender encoding (None).

**Pull request merged**
