### PR TITLE
adding release date films, models and data

### PR DESCRIPTION
**Pull request by carvilsi**
@phalt Hi Phalt.

I made those changes about the release date of films, on the model and data.

I am not familiar with django and I am not sure if those changes are 100% correct, sorry if I made  mistakes. In the other hand, I run the test:

> char@crunchbang:~/swapi$ make test
> python manage.py test
> Creating test database for alias 'default'...
> ....................
> ----------------------------------------------------------------------
> Ran 20 tests in 16.207s
> 
> OK

I hope that it will be useful. And thanks again for this great API ;)

Best regards.

### CODE REVIEW

**Comment by phalt** [comment]
If the tests pass, it probably works. :stuck_out_tongue_winking_eye: 

Can you update the documentation example to show the new attribute?

**Comment by carvilsi** [comment]
Great :)

I will try to update the documentation this afternoon.

**Comment by carvilsi** [comment]
Hi Phalt.

Already updated the documentation to show the new attribute. I hope that all is all right. In other case, please, tell me if any change is needed :smile:

**Comment by phalt** [comment]
Woo! Let's see if I can merge this.

**Comment by phalt** [comment]
Deployed and rolled out. Thank you!

**Comment by carvilsi** [comment]
Thanks to you!

:smile: 

Regards.

**Pull request merged**
